# Generated by Django 5.2.3 on 2025-06-24 14:02

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="AssemblyStage",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        choices=[
                            ("SUB_ASSEMBLY_1", "Sub Assembly 1"),
                            ("SUB_ASSEMBLY_2", "Sub Assembly 2"),
                            ("FINAL_ASSEMBLY", "Final Assembly"),
                        ],
                        max_length=50,
                        unique=True,
                    ),
                ),
                (
                    "display_name",
                    models.CharField(blank=True, max_length=100, null=True),
                ),
                ("description", models.TextField(blank=True, null=True)),
                ("order", models.PositiveIntegerField(default=1)),
            ],
            options={
                "ordering": ["order"],
            },
        ),
        migrations.CreateModel(
            name="Product",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("code", models.CharField(max_length=20, unique=True)),
                ("name", models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name="AssemblyProcess",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100)),
                (
                    "display_name",
                    models.CharField(blank=True, max_length=200, null=True),
                ),
                (
                    "location",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("ASSEMBLY_ROOM", "Assembly Room"),
                            ("OUTSIDE_ASSEMBLY_ROOM", "Outside Assembly Room"),
                        ],
                        max_length=30,
                        null=True,
                    ),
                ),
                ("order", models.PositiveIntegerField(default=1)),
                (
                    "is_looped",
                    models.BooleanField(
                        default=False, help_text="Should loop until manually advanced"
                    ),
                ),
                (
                    "loop_group",
                    models.CharField(
                        blank=True,
                        help_text="Group processes that loop together",
                        max_length=50,
                        null=True,
                    ),
                ),
                (
                    "stage",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="processes",
                        to="screen_app.assemblystage",
                    ),
                ),
            ],
            options={
                "ordering": ["stage__order", "order"],
                "unique_together": {("stage", "order")},
            },
        ),
        migrations.CreateModel(
            name="BillOfMaterial",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "bom_type",
                    models.CharField(
                        choices=[
                            ("SINGLE_UNIT", "Single Unit"),
                            ("BATCH_50", "50 Units"),
                            ("SUB_ASSEMBLY_1", "Sub Assembly 1"),
                            ("SUB_ASSEMBLY_2", "Sub Assembly 2"),
                            ("FINAL_ASSEMBLY", "Final Assembly"),
                        ],
                        max_length=20,
                    ),
                ),
                (
                    "file",
                    models.FileField(
                        upload_to="bom_files/",
                        validators=[
                            django.core.validators.FileExtensionValidator(
                                allowed_extensions=["pdf", "xlsx", "docx"]
                            )
                        ],
                    ),
                ),
                (
                    "stage",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="boms",
                        to="screen_app.assemblystage",
                    ),
                ),
                (
                    "product",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="boms",
                        to="screen_app.product",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="ProductMedia",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "media_type",
                    models.CharField(
                        choices=[
                            ("BOM", "Bill of Material"),
                            ("PROCESS_DOC", "Process Document"),
                            ("VIDEO", "Video"),
                            ("INSTRUCTION", "Instruction Manual"),
                        ],
                        default="PROCESS_DOC",
                        max_length=20,
                    ),
                ),
                (
                    "file",
                    models.FileField(
                        upload_to="product_media/",
                        validators=[
                            django.core.validators.FileExtensionValidator(
                                allowed_extensions=["pdf", "mp4", "mov", "xlsx", "docx"]
                            )
                        ],
                    ),
                ),
                (
                    "duration",
                    models.PositiveIntegerField(
                        blank=True,
                        default=15,
                        help_text="Duration in seconds (for videos)",
                    ),
                ),
                (
                    "display_screen_1",
                    models.BooleanField(
                        default=False, help_text="Show on Display Screen 1"
                    ),
                ),
                (
                    "display_screen_2",
                    models.BooleanField(
                        default=False, help_text="Show on Display Screen 2"
                    ),
                ),
                (
                    "display_screen_3",
                    models.BooleanField(
                        default=False, help_text="Show on Display Screen 3"
                    ),
                ),
                (
                    "bom",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="media",
                        to="screen_app.billofmaterial",
                    ),
                ),
                (
                    "process",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="media",
                        to="screen_app.assemblyprocess",
                    ),
                ),
                (
                    "product",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="media",
                        to="screen_app.product",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Station",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100)),
                (
                    "display_number",
                    models.PositiveIntegerField(
                        blank=True,
                        choices=[
                            (1, "Display Screen 1"),
                            (2, "Display Screen 2"),
                            (3, "Display Screen 3"),
                        ],
                        help_text="Which display screen this station represents",
                        null=True,
                    ),
                ),
                (
                    "product_quantity",
                    models.PositiveIntegerField(
                        default=50, help_text="Quantity being assembled"
                    ),
                ),
                (
                    "show_single_unit_bom",
                    models.BooleanField(
                        default=False, help_text="Show single unit BOM for reference"
                    ),
                ),
                (
                    "show_batch_bom",
                    models.BooleanField(
                        default=True, help_text="Show batch quantity BOM"
                    ),
                ),
                (
                    "clicker_enabled",
                    models.BooleanField(
                        default=True, help_text="Enable clicker support"
                    ),
                ),
                (
                    "auto_advance",
                    models.BooleanField(
                        default=False, help_text="Auto advance after media duration"
                    ),
                ),
                (
                    "loop_mode",
                    models.BooleanField(
                        default=False,
                        help_text="Currently in loop mode (for processes 1A, 1B, 1C)",
                    ),
                ),
                (
                    "current_process",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="active_stations",
                        to="screen_app.assemblyprocess",
                    ),
                ),
                (
                    "current_product",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="active_stations",
                        to="screen_app.product",
                    ),
                ),
                (
                    "current_stage",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="active_stations",
                        to="screen_app.assemblystage",
                    ),
                ),
                (
                    "manager",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "products",
                    models.ManyToManyField(
                        blank=True, related_name="stations", to="screen_app.product"
                    ),
                ),
            ],
            options={
                "unique_together": {("name", "display_number")},
            },
        ),
        migrations.CreateModel(
            name="AssemblySession",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("quantity", models.PositiveIntegerField()),
                ("start_time", models.DateTimeField(auto_now_add=True)),
                ("end_time", models.DateTimeField(blank=True, null=True)),
                ("completed", models.BooleanField(default=False)),
                (
                    "current_process",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="screen_app.assemblyprocess",
                    ),
                ),
                (
                    "current_stage",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="screen_app.assemblystage",
                    ),
                ),
                (
                    "product",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="screen_app.product",
                    ),
                ),
                (
                    "display_1_station",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="sessions_display_1",
                        to="screen_app.station",
                    ),
                ),
                (
                    "display_2_station",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="sessions_display_2",
                        to="screen_app.station",
                    ),
                ),
                (
                    "display_3_station",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="sessions_display_3",
                        to="screen_app.station",
                    ),
                ),
            ],
        ),
    ]
