# Generated by Django 5.1.1 on 2024-09-27 03:44

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=20, unique=True)),
                ('name', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='ProductMedia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(upload_to='product_media/', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['pdf', 'mp4', 'mov'])])),
                ('duration', models.PositiveIntegerField(blank=True, default=15, help_text='Duration in seconds (for videos)')),
                ('is_selected', models.BooleanField(default=False)),
                ('is_active', models.BooleanField(default=True)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='media', to='screen_app.product')),
            ],
        ),
        migrations.CreateModel(
            name='Station',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('manager', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('products', models.ManyToManyField(blank=True, related_name='stations', to='screen_app.product')),
                ('selected_media', models.ManyToManyField(blank=True, related_name='selected_stations', to='screen_app.productmedia')),
            ],
        ),
        migrations.AddField(
            model_name='productmedia',
            name='station',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='screen_app.station'),
        ),
        migrations.CreateModel(
            name='Linewise',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('product', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='screen_app.product')),
                ('stations', models.ManyToManyField(related_name='linewise_set', to='screen_app.station')),
            ],
        ),
    ]
