# Generated by Django 5.1.1 on 2024-09-27 04:59

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('screen_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productmedia',
            name='station',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='screen_app.station'),
        ),
    ]
