# Generated by Django 5.2.3 on 2025-07-02 15:37

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("screen_app", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="BOMItem",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "item_code",
                    models.CharField(
                        help_text="Internal item code for tracking",
                        max_length=50,
                        unique=True,
                    ),
                ),
                ("item_description", models.CharField(max_length=200)),
                (
                    "part_number",
                    models.CharField(
                        help_text="Part number (can be B.O. for bought out)",
                        max_length=50,
                    ),
                ),
                (
                    "unit_of_measure",
                    models.CharField(
                        default="NO.",
                        help_text="Unit (NO., KGS, GM, etc.)",
                        max_length=20,
                    ),
                ),
                (
                    "item_photo",
                    models.ImageField(
                        blank=True,
                        help_text="Item photograph",
                        null=True,
                        upload_to="bom_items/",
                    ),
                ),
                ("supplier", models.CharField(blank=True, max_length=100, null=True)),
                (
                    "cost_per_unit",
                    models.DecimalField(
                        blank=True, decimal_places=4, max_digits=10, null=True
                    ),
                ),
                (
                    "weight_per_unit",
                    models.DecimalField(
                        blank=True,
                        decimal_places=4,
                        help_text="Weight in KG",
                        max_digits=8,
                        null=True,
                    ),
                ),
                ("created_date", models.DateTimeField(auto_now_add=True)),
                ("updated_date", models.DateTimeField(auto_now=True)),
                ("is_active", models.BooleanField(default=True)),
            ],
            options={
                "ordering": ["item_description"],
            },
        ),
        migrations.AddField(
            model_name="billofmaterial",
            name="source_type",
            field=models.CharField(
                choices=[("PDF", "PDF File"), ("DATABASE", "Database Template")],
                default="DATABASE",
                max_length=10,
            ),
        ),
        migrations.AlterField(
            model_name="billofmaterial",
            name="file",
            field=models.FileField(
                blank=True,
                null=True,
                upload_to="bom_files/",
                validators=[
                    django.core.validators.FileExtensionValidator(
                        allowed_extensions=["pdf", "xlsx", "docx"]
                    )
                ],
            ),
        ),
        migrations.AlterField(
            model_name="productmedia",
            name="file",
            field=models.FileField(
                blank=True,
                null=True,
                upload_to="product_media/",
                validators=[
                    django.core.validators.FileExtensionValidator(
                        allowed_extensions=["pdf", "mp4", "mov", "xlsx", "docx"]
                    )
                ],
            ),
        ),
        migrations.CreateModel(
            name="BOMTemplate",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "bom_type",
                    models.CharField(
                        choices=[
                            ("SINGLE_UNIT", "Single Unit"),
                            ("BATCH_50", "50 Units"),
                            ("SUB_ASSEMBLY_1", "Sub Assembly 1"),
                            ("SUB_ASSEMBLY_2", "Sub Assembly 2"),
                            ("FINAL_ASSEMBLY", "Final Assembly"),
                        ],
                        max_length=20,
                    ),
                ),
                ("template_name", models.CharField(max_length=100)),
                ("description", models.TextField(blank=True, null=True)),
                (
                    "display_screen_1",
                    models.BooleanField(
                        default=False, help_text="Show on Display Screen 1"
                    ),
                ),
                (
                    "display_screen_2",
                    models.BooleanField(
                        default=False, help_text="Show on Display Screen 2"
                    ),
                ),
                (
                    "display_screen_3",
                    models.BooleanField(
                        default=False, help_text="Show on Display Screen 3"
                    ),
                ),
                ("created_date", models.DateTimeField(auto_now_add=True)),
                ("is_active", models.BooleanField(default=True)),
                (
                    "product",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="bom_templates",
                        to="screen_app.product",
                    ),
                ),
                (
                    "stage",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="bom_templates",
                        to="screen_app.assemblystage",
                    ),
                ),
            ],
            options={
                "ordering": ["product", "bom_type"],
                "unique_together": {("product", "bom_type", "stage")},
            },
        ),
        migrations.AddField(
            model_name="billofmaterial",
            name="bom_template",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="screen_app.bomtemplate",
            ),
        ),
        migrations.CreateModel(
            name="BOMTemplateItem",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "base_quantity",
                    models.DecimalField(
                        decimal_places=4,
                        help_text="Quantity for single unit",
                        max_digits=10,
                    ),
                ),
                ("serial_number", models.PositiveIntegerField(help_text="S.NO in BOM")),
                (
                    "notes",
                    models.TextField(
                        blank=True, help_text="Special instructions or notes", null=True
                    ),
                ),
                ("is_active", models.BooleanField(default=True)),
                (
                    "bom_template",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="bom_items",
                        to="screen_app.bomtemplate",
                    ),
                ),
                (
                    "item",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="screen_app.bomitem",
                    ),
                ),
            ],
            options={
                "ordering": ["serial_number"],
                "unique_together": {("bom_template", "serial_number")},
            },
        ),
    ]
