# Generated by Django 5.1.1 on 2024-09-27 05:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('screen_app', '0002_alter_productmedia_station'),
    ]

    operations = [
        migrations.AddField(
            model_name='station',
            name='screen_name',
            field=models.CharField(blank=True, max_length=400),
        ),
    ]
