# Generated by Django 5.2.3 on 2025-07-13 20:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("screen_app", "0002_bomitem_billofmaterial_source_type_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="assemblystage",
            name="name",
            field=models.CharField(
                choices=[
                    ("SUB_ASSEMBLY_1", "Sub Assembly 1"),
                    ("BOM", "Bom"),
                    ("SUB_ASSEMBLY_2", "Sub Assembly 2"),
                    ("FINAL_ASSEMBLY", "Final Assembly"),
                ],
                max_length=50,
                unique=True,
            ),
        ),
    ]
