# Generated by Django 5.1.1 on 2024-09-27 07:16

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('screen_app', '0003_station_screen_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productmedia',
            name='file',
            field=models.FileField(upload_to='product_media/', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['pdf', 'mp4', 'mov', 'zip'])]),
        ),
    ]
