# Generated by Django 5.2.3 on 2025-07-25 07:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("screen_app", "0004_alter_assemblystage_name"),
    ]

    operations = [
        migrations.AddField(
            model_name="station",
            name="auto_loop_mode",
            field=models.BooleanField(
                default=False,
                help_text="Auto-loop mode for processes 1A, 1B, 1C with duration-based switching",
            ),
        ),
        migrations.AlterField(
            model_name="station",
            name="loop_mode",
            field=models.BooleanField(
                default=False, help_text="Currently in loop mode"
            ),
        ),
    ]
