# Generated by Django 5.2.3 on 2025-07-25 07:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("screen_app", "0005_station_auto_loop_mode_alter_station_loop_mode"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="station",
            name="auto_loop_mode",
        ),
        migrations.AlterField(
            model_name="station",
            name="loop_mode",
            field=models.BooleanField(
                default=False,
                help_text="Currently in loop mode (for processes 1A, 1B, 1C)",
            ),
        ),
    ]
