# Generated by Django 5.2.3 on 2025-07-31 07:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("screen_app", "0006_remove_station_auto_loop_mode_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="bomtemplate",
            name="duration",
            field=models.PositiveIntegerField(
                blank=True, default=20, help_text="Duration in seconds"
            ),
        ),
        migrations.AddField(
            model_name="bomtemplate",
            name="is_duration_active",
            field=models.BooleanField(
                blank=True,
                default=False,
                help_text="Should loop until manually advanced",
            ),
        ),
    ]
