# Generated by Django 5.2.3 on 2025-06-24 11:55

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("screen_app", "0006_alter_productmedia_file"),
    ]

    operations = [
        migrations.CreateModel(
            name="Refresher",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "time_duration",
                    models.IntegerField(
                        blank=True,
                        default=3,
                        help_text="Duration in minutes (for updating the page )",
                    ),
                ),
            ],
        ),
        migrations.RemoveField(
            model_name="productmedia",
            name="is_active",
        ),
        migrations.RemoveField(
            model_name="productmedia",
            name="is_selected",
        ),
        migrations.RemoveField(
            model_name="productmedia",
            name="station",
        ),
        migrations.RemoveField(
            model_name="station",
            name="screen_name",
        ),
        migrations.AlterField(
            model_name="productmedia",
            name="file",
            field=models.FileField(
                upload_to="product_media/",
                validators=[
                    django.core.validators.FileExtensionValidator(
                        allowed_extensions=["pdf", "mp4", "mov"]
                    )
                ],
            ),
        ),
        migrations.AlterField(
            model_name="station",
            name="selected_media",
            field=models.ManyToManyField(
                blank=True, related_name="stations", to="screen_app.productmedia"
            ),
        ),
        migrations.DeleteModel(
            name="Linewise",
        ),
    ]
