# Generated by Django 5.2.3 on 2025-07-31 08:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("screen_app", "0007_bomtemplate_duration_bomtemplate_is_duration_active"),
    ]

    operations = [
        migrations.AlterField(
            model_name="bomtemplateitem",
            name="base_quantity",
            field=models.DecimalField(
                decimal_places=4,
                default=1,
                help_text="Quantity for single unit",
                max_digits=10,
            ),
        ),
    ]
