# Generated by Django 5.2.3 on 2025-08-06 18:29

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("screen_app", "0008_alter_bomtemplateitem_base_quantity"),
    ]

    operations = [
        migrations.AddField(
            model_name="assemblystage",
            name="product",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="assembly_product",
                to="screen_app.product",
            ),
        ),
        migrations.AlterField(
            model_name="assemblystage",
            name="name",
            field=models.CharField(max_length=500),
        ),
    ]
