# Generated by Django 5.2.3 on 2025-08-06 19:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("screen_app", "0009_assemblystage_product_alter_assemblystage_name"),
    ]

    operations = [
        migrations.AlterField(
            model_name="bomtemplate",
            name="bom_type",
            field=models.CharField(max_length=200),
        ),
    ]
