# Generated by Django 5.2.3 on 2025-08-06 20:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("screen_app", "0010_alter_bomtemplate_bom_type"),
    ]

    operations = [
        migrations.AlterField(
            model_name="billofmaterial",
            name="bom_type",
            field=models.CharField(max_length=200),
        ),
    ]
