# Generated by Django 5.2.3 on 2025-08-07 11:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("screen_app", "0014_alter_bomtemplate_bom_type"),
    ]

    operations = [
        migrations.AlterField(
            model_name="bomtemplate",
            name="bom_type",
            field=models.CharField(
                choices=[
                    ("SINGLE_UNIT", "Single Unit"),
                    ("BATCH_50", "50 Unitswwwwwwwwwwww"),
                    ("SUB_ASSEMBLY_1", "Sub Assembly 1"),
                    ("SUB_ASSEMBLY_2", "Sub Assembly 2"),
                    ("FINAL_ASSEMBLY", "Final Assembly"),
                ],
                max_length=20,
            ),
        ),
    ]
