# Generated by Django 5.2.3 on 2025-08-07 11:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("screen_app", "0015_alter_bomtemplate_bom_type"),
    ]

    operations = [
        migrations.AlterField(
            model_name="bomtemplate",
            name="bom_type",
            field=models.CharField(
                choices=[
                    ("BATCH_50", "50 Unit"),
                    ("SUB_ASSEMBLY", "Sub Assembly "),
                    ("FINAL_ASSEMBLY", "Final Assembly"),
                ],
                max_length=20,
            ),
        ),
    ]
