# Generated by Django 5.2.3 on 2025-08-07 11:37

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("screen_app", "0017_alter_bomtemplate_bom_type"),
    ]

    operations = [
        migrations.AlterField(
            model_name="productmedia",
            name="bom",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="media",
                to="screen_app.bomtemplate",
            ),
        ),
    ]
