# Generated by Django 5.2.3 on 2025-08-18 20:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("screen_app", "0019_alter_productmedia_bom"),
    ]

    operations = [
        migrations.AlterField(
            model_name="bomtemplate",
            name="bom_type",
            field=models.CharField(
                help_text="Custom BOM type name (e.g., 'Single Unit', 'Batch 100', 'Custom Assembly')",
                max_length=100,
            ),
        ),
    ]
