# Generated by Django 5.2.3 on 2025-08-19 11:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("screen_app", "0021_alter_bomtemplate_bom_type"),
    ]

    operations = [
        migrations.AlterField(
            model_name="billofmaterial",
            name="bom_type",
            field=models.CharField(
                choices=[
                    ("SINGLE_UNIT", "Single Unit"),
                    ("BATCH_50", "50 Units"),
                    ("SUB_ASSEMBLY_1", "Sub Assembly 1"),
                    ("SUB_ASSEMBLY_2", "Sub Assembly 2"),
                    ("SUB_ASSEMBLY_3", "Sub Assembly 3"),
                    ("SUB_ASSEMBLY_4", "Sub Assembly 4"),
                    ("FINAL_ASSEMBLY", "Final Assembly"),
                ],
                max_length=20,
            ),
        ),
    ]
