# Generated by Django 5.2.3 on 2025-08-22 17:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("screen_app", "0023_alter_bomtemplate_bom_type"),
    ]

    operations = [
        migrations.CreateModel(
            name="Bomtype",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("type", models.CharField(blank=True, max_length=50, null=True)),
            ],
        ),
    ]
