# Generated by Django 5.2.3 on 2025-08-22 17:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("screen_app", "0024_bomtype"),
    ]

    operations = [
        migrations.DeleteModel(
            name="Bomtype",
        ),
    ]
