# Generated by Django 5.2.3 on 2025-11-07 21:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("screen_app", "0025_delete_bomtype"),
    ]

    operations = [
        migrations.AddField(
            model_name="station",
            name="bom_page_updated_at",
            field=models.DateTimeField(
                auto_now=True, help_text="Last time BOM page was changed"
            ),
        ),
        migrations.AddField(
            model_name="station",
            name="current_bom_page",
            field=models.PositiveIntegerField(
                default=1, help_text="Current BOM page number (shared across displays)"
            ),
        ),
    ]
